#use latest docker image
image: docker:latest

services:
  - docker:dind

stages:
  - build
  - deploy
before_script:
  # Login to Gitlab container Registry
  - echo $CI_JOB_TOKEN | docker login -u gitlab-ci-token $CI_REGISTRY --password-stdin

build:
  stage: build
  only:
    refs:
      - master
  script:
    # Build and tag image for  Gitlab registries
    - docker build -t $CI_REGISTRY_IMAGE/$CI_PROJECT_NAME:latest .

      # Push image to Gitlab registry
    - docker push $CI_REGISTRY_IMAGE/$CI_PROJECT_NAME:latest

deploy:
  stage: deploy
  only:
    refs:
      - master
  image: alpine
  environment:
    name: staging
  before_script:
    - apk add openssh-client
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -e "$DEPLOY_KEY_PRIVATE" > ~/.ssh/id_rsa
    - chmod 700 ~/.ssh/id_rsa
    - echo "$DEPLOY_KEY_PRIVATE" | tr -d '\r' | ssh-add -
  script:
    - |
      ssh -o StrictHostKeyChecking=no "$DEPLOY_USER@$DEPLOY_HOST" ""$DEPLOY_COMMAND""


#include:
#  - template: Security/SAST.gitlab-ci.yml
